### ISSUE TITLE
IP address like 1.1.1.1d should not be valid

### ISSUE THREAD

**Issue by ellucianBret** [miguelmota/is-valid-host#2] opened 2020-11-23 21:25 UTC
I like how nice and simple your code is but allowing IP addresses with no numerics should not be valid.

Thx,
Bret

**Comment by miguelmota** [comment] 2020-12-23 00:25
@ellucianBret `1.1.1.1d` can be a valid host (ie by editting /etc/hosts). There are no TLDs that start with a number however the specification allows for it.

![Screenshot from 2020-12-22 16-09-01](https://user-images.githubusercontent.com/168240/102944977-4ab06700-4471-11eb-9ce6-3024e07cbabd.png)

If you need to strictly check if it's a valid IP or domain name then a suggestion is to use libraries like `is-valid-domain` and `is-valid-ip` and a step further would be to query DNS to check if it's accessible.

Closing issue since it's expected behavior.

**Closed as completed** 2020-12-23 00:27 UTC
